const ADD_DATA = 'ADD_DATA';
const SELECT_ALBUM = 'SELECT_ALBUM';
const ADD_IMAGE_TO_FAVOURITES = 'ADD_IMAGE_TO_FAVOURITES';
const REMOVE_IMAGE_FROM_FAVOURITES = 'REMOVE_IMAGE_FROM_FAVOURITES';
const SET_IS_IMAGE_FAVED = 'SET_IS_IMAGE_FAVED';
const SET_IMAGE_FAVED = 'SET_IMAGE_FAVED';
const SET_IMAGE_UNFAVED = 'SET_IMAGE_UNFAVED';

export {
  ADD_DATA,
  SELECT_ALBUM,
  ADD_IMAGE_TO_FAVOURITES,
  REMOVE_IMAGE_FROM_FAVOURITES,
  SET_IS_IMAGE_FAVED,
  SET_IMAGE_FAVED,
  SET_IMAGE_UNFAVED
}